base/urls.py
from django.urls import path
from base import views

app_name = 'base'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('deposit-withdraw/', views.DepositWithdrawView.as_view(), name= 'deposit_withdraw'),
    path('transfer/', views.VerifyTransferView.as_view(), name= 'transfer'),
]

transactions/urls.py
from django.urls import path
from transactions import views

app_name = 'transactions'

urlpatterns = [
    path('', views.TransactionView.as_view(), name='transactions'),
    path('download/', views.download_transaction_pdf, name='download'),
]

vbank/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('', include('base.urls', namespace='base')),
    path('accounts/', include('allauth.urls')),
    
    path('admin/', admin.site.urls),
    path('transactions/', include('transactions.urls', namespace='transactions')),
]



if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from vbank.settings.helpers.image_helper import get_upload_path
import random
# Create your models here.



class User(AbstractUser):
    pass


class Account(models.Model):
    user = models.OneToOneField('accounts.User', on_delete=models.CASCADE)
    number = models.CharField(max_length=12, unique=True, default=1)
    balance = models.DecimalField(max_digits=50, decimal_places=2, default=0)

    def __str__(self):
        return f'{self.user.email} account'
    

base/models.py
from django.db import models

# Create your models here.

transactions/models.py
from django.db import models
from vbank.settings.helpers import model_helper
# Create your models here.
class Transaction(model_helper.TimeBasedModel):
    class TransactionTypeChoice(models.TextChoices):
        credit = 'Credit', 'Credit'
        debit = 'Debit', 'Debit'
    user = models.ForeignKey('accounts.User', on_delete=models.CASCADE)
    desc = models.TextField()
    type = models.CharField(max_length=20, default=TransactionTypeChoice.credit,
    choices=TransactionTypeChoice.choices)

    def __str__(self):
        return f'{self.user.get_full_name()} transaction'

accounts/views.py
from django.shortcuts import render

# Create your views here.

base/views.py
from django.http.response import JsonResponse
from django.shortcuts import redirect, render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View
import decimal, datetime
from accounts.models import Account
from django.contrib import messages
from transactions.models import Transaction
from base.utils import greeting

# Create your views here.


class IndexView(LoginRequiredMixin, View):
    template_name = 'index.html'
    def get(self, request, *args, **kwargs):
        currentTime = datetime.datetime.now()
        context = {
            'greeting' : greeting(currentTime),
        }
        return render(request, self.template_name, context)


class DepositWithdrawView(LoginRequiredMixin,View):
    def post(self, request, *args, **kwargs):
        if request.is_ajax():
            ajaxData = request.POST
            data = {}
            action = ajaxData['action']
            amount = ajaxData['amount']
            transaction = Transaction()
            transaction.user = self.request.user
            if action.lower() == 'deposit':
                self.request.user.account.balance += decimal.Decimal(amount)
                transaction.desc = f'You deposited ${amount}'
                transaction.type = Transaction.TransactionTypeChoice.credit
            else:
                self.request.user.account.balance -= decimal.Decimal(amount)
                transaction.desc = f'You Withdrew ${amount}'
                transaction.type = Transaction.TransactionTypeChoice.debit
            self.request.user.account.save()
            transaction.save()
            data['message'] = f'{action} of ${amount} was successful'
            data['amount'] = amount
            data['availableBalance'] = self.request.user.account.balance
            return JsonResponse(data, safe=False)


class VerifyTransferView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        if request.is_ajax():
            data = {}
            data['error'] = False
            ajaxData = request.GET
            try:
                accountNumber = ajaxData['accountNumber']
                account = Account.objects.get(number=accountNumber)
                data['name'] = account.user.get_full_name()
                if account == self.request.user.account:
                    data['name'] = 'You can\'t transfer to your Account, Try Deposit'
                    data['error']= True 
            except:
                data['name'] = 'Account Not Found'
                data['error'] = True
            return JsonResponse(data, safe=False)
    
    def post(self, request, *args, **kwargs):
        ajaxData = request.POST
        amount = ajaxData['amount']
        senderTransaction = Transaction()
        receiverTransaction = Transaction()
        senderTransaction.user = self.request.user
        senderTransaction.type = Transaction.TransactionTypeChoice.debit
        receiverTransaction.type = Transaction.TransactionTypeChoice.credit
        account = Account.objects.get(number=ajaxData['accountNumber'])
        receiverTransaction.user = account.user
        receiverTransaction.desc = f'You received {amount} from {self.request.user.get_full_name()} with account number {self.request.user.account.number}'
        account.balance += decimal.Decimal(amount)
        account.save()
        receiverTransaction.save()
        self.request.user.account.balance -= decimal.Decimal(amount)
        senderTransaction.desc = f'You sent {amount} to {account.user.get_full_name()} with account number {account.number}'
        senderTransaction.save()
        self.request.user.account.save()
        messages.success(request, f'Transfer of {amount} to {account.user.get_full_name()}')
        return redirect('base:index')

transactions/views.py
from django.http.response import HttpResponse
from django.shortcuts import render
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin
from transactions.models import Transaction
from transactions.utils import render_to_pdf
# Create your views here.


class TransactionView(LoginRequiredMixin,View):
    template_name = 'transactions.html'
    def get(self, request, *args, **kwargs):
        context = {
            'transactions': Transaction.objects.filter(user=self.request.user).order_by('-created_at')
        }
        return render(request, self.template_name, context)
    
def download_transaction_pdf(request):
    transactions = Transaction.objects.filter(user=request.user).order_by('-created_at')
    context = {
        'transactions':transactions
    }
    pdf = render_to_pdf('transaction_pdf.html', context)
    return HttpResponse(pdf, content_type='application/pdf')

base/templates/index.html
{% extends 'partials/_layout.html' %} 
{% load static humanize %}
{% block page_title %} Home {% endblock %}
{% block content %}

{% include 'partials/_sidebar.html' %}
{% include 'partials/_navbar.html' %}
<div class="content-page">
  <div class="messageAlert">
    {% for message in messages %}
    <div class="alert text-white bg-primary" role="alert">
      <div class="iq-alert-text">{{message}}</div>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <i class="ri-close-line"></i>
      </button>
    </div>
    {% endfor %}
  </div>

  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-8">
        <div
          class="card card-transparent card-block card-stretch card-height border-none"
        >
          <div class="card-body p-0 mt-lg-2 mt-0">
            <h3 class="mb-3">Hi {{user.last_name}}, {{greeting.title}}</h3>
            <p class="mb-0 mr-4">
              Your dashboard gives you views of key performance or transaction
              process.
            </p>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="card card-block card-stretch card-height">
          <div class="card-body">
            <div class="d-flex align-items-center mb-4 card-total-sale">
              <div class="icon iq-icon-box-2 bg-success-light">
                <i class="fas fa-dollar-sign"></i>
              </div>
              <div>
                <p class="mb-2">Available Balance</p>
                <h4 class="m-0 userBalance">{{user.account.balance | intcomma}}</h4>
                <small><strong>A/N: {{user.account.number}}</strong></small>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="card card-block card-stretch card-height">
          <div class="card-body">
            <div class="d-flex align-items-center card-total-sale">
              <div class="icon iq-icon-box-2 bg-success-light">
                <i class="fas fa-coins"></i>

              </div>
              <div>
                <h5 class="mb-2 font-weight-bolder text-uppercase">Deposit</h5>
                <a href="#" data-action="Deposit" onclick="depositWithdraw(this)" data-toggle="modal" data-target="#depositWithdrawModalCenter">Start Here</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="card card-block card-outline-primary card-stretch card-height">
          <div class="card-body">
            <div class="d-flex align-items-center card-total-sale">
              <div class="icon iq-icon-box-2 bg-success-light">
                <i class="fas fa-money-check-alt"></i>
              </div>
              <div>
                <h5 class="mb-2 font-weight-bolder text-uppercase">withdraw</h5>
                <a href="#" data-action="Withdraw" onclick="depositWithdraw(this)" data-toggle="modal" data-target="#depositWithdrawModalCenter">Start Here</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="card card-block card-stretch card-height">
          <div class="card-body">
            <div class="d-flex align-items-center card-total-sale">
              <div class="icon iq-icon-box-2 bg-success-light">
                <i class="fas fa-hand-holding-usd"></i>
              </div>
              <div>
                <h5 class="mb-2 font-weight-bolder text-uppercase">transfer</h5>
                <a href="#" data-toggle="modal" data-target="#transferModalCenter">Start Here</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="card card-block card-stretch card-height-helf">
          <div class="card-body">
            <div class="d-flex align-items-top justify-content-between">
              <div class="">
                <p class="mb-0">Deposit/Transfers</p>
                <h5>$ 98,7800 K</h5>
              </div>
              <div class="card-header-toolbar d-flex align-items-center">
                <div class="dropdown">
                  <span
                    class="dropdown-toggle dropdown-bg btn"
                    id="dropdownMenuButton003"
                    data-toggle="dropdown"
                  >
                    This Month<i class="ri-arrow-down-s-line ml-1"></i>
                  </span>
                  <div
                    class="dropdown-menu dropdown-menu-right shadow-none"
                    aria-labelledby="dropdownMenuButton003"
                  >
                    <a class="dropdown-item" href="#">Year</a>
                    <a class="dropdown-item" href="#">Month</a>
                    <a class="dropdown-item" href="#">Week</a>
                  </div>
                </div>
              </div>
            </div>
            <div id="layout1-chart-3" class="layout-chart-1"></div>
          </div>
        </div>
        <div class="card card-block card-stretch card-height-helf">
          <div class="card-body">
            <div class="d-flex align-items-top justify-content-between">
              <div class="">
                <p class="mb-0">Withdrawals/Transfers</p>
                <h5>$ 45,8956 K</h5>
              </div>
              <div class="card-header-toolbar d-flex align-items-center">
                <div class="dropdown">
                  <span
                    class="dropdown-toggle dropdown-bg btn"
                    id="dropdownMenuButton004"
                    data-toggle="dropdown"
                  >
                    This Month<i class="ri-arrow-down-s-line ml-1"></i>
                  </span>
                  <div
                    class="dropdown-menu dropdown-menu-right shadow-none"
                    aria-labelledby="dropdownMenuButton004"
                  >
                    <a class="dropdown-item" href="#">Year</a>
                    <a class="dropdown-item" href="#">Month</a>
                    <a class="dropdown-item" href="#">Week</a>
                  </div>
                </div>
              </div>
            </div>
            <div id="layout1-chart-4" class="layout-chart-2"></div>
          </div>
        </div>
      </div>
      <div class="col-lg-8">
        <div class="card card-block card-stretch card-height">
          <div class="card-header d-flex justify-content-between">
            <div class="header-title">
              <h4 class="card-title">Account Summary</h4>
            </div>
            <div class="card-header-toolbar d-flex align-items-center">
              <div class="dropdown">
                <span
                  class="dropdown-toggle dropdown-bg btn"
                  id="dropdownMenuButton005"
                  data-toggle="dropdown"
                >
                  This Month<i class="ri-arrow-down-s-line ml-1"></i>
                </span>
                <div
                  class="dropdown-menu dropdown-menu-right shadow-none"
                  aria-labelledby="dropdownMenuButton005"
                >
                  <a class="dropdown-item" href="#">Year</a>
                  <a class="dropdown-item" href="#">Month</a>
                  <a class="dropdown-item" href="#">Week</a>
                </div>
              </div>
            </div>
          </div>
          <div class="card-body">
            <div class="d-flex flex-wrap align-items-center mt-2">
              <div class="d-flex align-items-center progress-order-left">
                <div
                  class="progress progress-round m-0 orange conversation-bar"
                  data-percent="46"
                >
                  <span class="progress-left">
                    <span class="progress-bar"></span>
                  </span>
                  <span class="progress-right">
                    <span class="progress-bar"></span>
                  </span>
                  <div class="progress-value text-secondary">46%</div>
                </div>
                <div class="progress-value ml-3 pr-5 border-right">
                  <h5>$12,6598</h5>
                  <p class="mb-0">Average Withdrawal</p>
                </div>
              </div>
              <div class="d-flex align-items-center ml-5 progress-order-right">
                <div
                  class="progress progress-round m-0 primary conversation-bar"
                  data-percent="46"
                >
                  <span class="progress-left">
                    <span class="progress-bar"></span>
                  </span>
                  <span class="progress-right">
                    <span class="progress-bar"></span>
                  </span>
                  <div class="progress-value text-primary">46%</div>
                </div>
                <div class="progress-value ml-3">
                  <h5>$59,8478</h5>
                  <p class="mb-0">Top Withdrawals</p>
                </div>
              </div>
            </div>
          </div>
          <div class="card-body pt-0">
            <div id="layout1-chart-5"></div>
          </div>
        </div>
      </div>
    </div>
    <!-- Page end  -->
  </div>
</div>
{% include 'partials/_deposit_withdraw_modal.html' %}
{% include 'partials/_transfer_modal.html' %}
{% endblock %} {% block customscripts %}
<script>

  const depositWithdraw = e => {
    const {action} = e.dataset
    action == 'Deposit' ? document.querySelector('#depositWithdrawAmount').removeAttribute('max') : document.querySelector('#depositWithdrawAmount').setAttribute('max', $('.userBalance').text())
    document.querySelector('.depositWithdrawTitle').textContent = action
    document.querySelector('.actionBtn').textContent = action
  }

  const handleRecaptcha = e => {
    const {value} = e
    const recaptcha = document.querySelector('#recaptcha').textContent
    value === recaptcha ? document.querySelector('.actionBtn').disabled =false : ''
  }

  document.querySelector('#depositWithdrawForm').addEventListener('submit', e => {
    e.preventDefault();
    const amount = $('#depositWithdrawAmount').val()
    const action = $('.actionBtn').text()
    $.ajax({
      url : "{% url 'base:deposit_withdraw' %}",
      method : 'POST',
      headers : {'X-CSRFToken':"{{csrf_token}}"},
      data : {amount : amount, action : action},
      success : res => {

        $('#depositWithdrawAmount').val('')
        $('#recaptchaDepositWithdraw').val('')
        $('.userBalance').text(res.availableBalance)
        $('#depositWithdrawModalCenter').modal('hide')
        $('.messageAlert').append(`
        <div class="alert text-white bg-primary" role="alert">
          <div class="iq-alert-text">${res.message}</div>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <i class="ri-close-line"></i>
          </button>
        </div>
        `)
      },
      error : err => {
        $('.messageAlert').append(`
        <div class="alert text-white bg-danger" role="alert">
          <div class="iq-alert-text">Error Occurred</div>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <i class="ri-close-line"></i>
          </button>
        </div>
        `)
      }
    })
  })
  const verifyAccount = e => {
    const {value} = e
    $.ajax({
      url : "{% url 'base:transfer' %}",
      method : 'GET',
      data : {accountNumber : value},
      success : res => {
        document.querySelector('.anDetails').textContent = res.name
        res.error ? document.querySelector('.actionTBtn').disabled = true :  document.querySelector('.actionTBtn').disabled = false
      },
      error : err => {
        $('.messageAlert').append(`
        <div class="alert text-white bg-primary" role="alert">
          <div class="iq-alert-text">${res.message}</div>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <i class="ri-close-line"></i>
          </button>
        </div>
        `)
      }
    })
  }
</script>

{% endblock customscripts %}

base/templates/partials/_deposit_withdraw_modal.html
<div class="modal fade" id="depositWithdrawModalCenter" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
       <div class="modal-content">
        <form action="" method="POST" id="depositWithdrawForm" >
           {% csrf_token %}
          <div class="modal-header">
             <h5 class="modal-title depositWithdrawTitle" id="exampleModalCenterTitle">Modal title</h5>
             <button type="button" class="close" data-dismiss="modal" aria-label="Close">
             <span aria-hidden="true">&times;</span>
             </button>
          </div>
          <div class="modal-body">
              
                  <div>
                    <label for="">Amount</label>
                    <input type="number" name="amount" id="depositWithdrawAmount" class="form-control" min="0" max="{{user.account.balance}}">
                  </div>
                  <div>
                    <label for="">Type the following <strong id="recaptcha">{{user.email}}/vbank</strong> </label>
                    <input type="text" name="" id="recaptchaDepositWithdraw" class="form-control" onkeyup="handleRecaptcha(this)">
                  </div>
              
          </div>
          <div class="modal-footer">
             <button type="submit" class="btn btn-primary actionBtn" disabled>Save changes</button>
          </div>
        </form>
       </div>
    </div>
 </div>

base/templates/partials/_layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <title>VRBank | {% block page_title %} {% endblock %}</title>

    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" />
    {% include 'partials/_stylesheet.html' %}
    {% block customstyles %}{% endblock %}
  </head>
  <body class="  ">
    <!-- loader Start -->
    <div id="loading">
      <div id="loading-center"></div>
    </div>
    <!-- loader END -->
    <!-- Wrapper Start -->
    <div class="wrapper">
    {% block content %}

    {% endblock content %}
    {% include 'partials/_script.html' %}
    {% block customscripts %}{% endblock customscripts %}
  </body>
</html>

base/templates/partials/_script.html
{% load static %}

<!-- Backend Bundle JavaScript -->
<script src="{% static 'js/backend-bundle.min.js' %}"></script>

<!-- Table Treeview JavaScript -->
<script src="{% static 'js/table-treeview.js' %}"></script>

<!-- Chart Custom JavaScript -->
<script src="{% static 'js/customizer.js' %}"></script>

<!-- Chart Custom JavaScript -->
<script async src="{% static 'js/chart-custom.js' %}"></script>

<!-- app JavaScript -->
<script src="{% static 'js/app.js' %}"></script>

base/templates/partials/_sidebar.html
{% load static %}
<div class="iq-sidebar  sidebar-default ">
  <div
    class="iq-sidebar-logo d-flex align-items-center justify-content-between"
  >
    <a href="{% url 'base:index' %}" class="header-logo">
      <img
        src="{% static 'images/logo.png' %}"
        class="img-fluid rounded-normal light-logo"
        alt="logo"
      />
      <h5 class="logo-title light-logo ml-3">VRBank</h5>
    </a>
    <div class="iq-menu-bt-sidebar ml-0">
      <i class="las la-bars wrapper-menu"></i>
    </div>
  </div>
  <div class="data-scrollbar" data-scroll="1">
    <nav class="iq-sidebar-menu">
      <ul id="iq-sidebar-toggle" class="iq-menu">
        <li class="active">
          <a href="{% url 'base:index' %}" class="svg-icon">
            <svg
              class="svg-icon"
              id="p-dash1"
              width="20"
              height="20"
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
            >
              <path
                d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"
              ></path>
              <polyline points="3.27 6.96 12 12.01 20.73 6.96"></polyline>
              <line x1="12" y1="22.08" x2="12" y2="12"></line>
            </svg>
            <span class="ml-4">Dashboard</span>
          </a>
        </li>
        <li class="">
          <a href="{% url 'transactions:transactions' %}" class="svg-icon">
            <svg
              class="svg-icon"
              id="p-dash1"
              width="20"
              height="20"
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
            >
              <path
                d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"
              ></path>
              <polyline points="3.27 6.96 12 12.01 20.73 6.96"></polyline>
              <line x1="12" y1="22.08" x2="12" y2="12"></line>
            </svg>
            <span class="ml-4">Transaction History</span>
          </a>
        </li>
      </ul>
    </nav>
    <div id="sidebar-bottom" class="position-relative sidebar-bottom">
      <div class="card border-none">
        <div class="card-body p-0">
          <div class="sidebarbottom-content">
            <div class="image">
              <img
                src="{% static 'images/layouts/side-bkg.png' %}"
                class="img-fluid"
                alt="side-bkg"
              />
            </div>
            <h6 class="mt-4 px-4 body-title">Get More Feature by Upgrading</h6>
            <button type="button" class="btn sidebar-bottom-btn mt-4">
              Go Premium
            </button>
          </div>
        </div>
      </div>
    </div>
    <div class="p-3"></div>
  </div>
</div>

base/templates/partials/_stylesheet.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/backend-plugin.min.css' %}">
<link rel="stylesheet" href="{% static 'css/backend.css?v=1.0.0' %}">
<link rel="stylesheet" href="{% static 'vendor/@fortawesome/fontawesome-free/css/all.min.css' %}">
<link rel="stylesheet" href="{% static 'vendor/line-awesome/dist/line-awesome/css/line-awesome.min.css' %}">
<link rel="stylesheet" href="{% static 'vendor/remixicon/fonts/remixicon.css' %}">

base/templates/partials/_transfer_modal.html
<div class="modal fade" id="transferModalCenter" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
       <div class="modal-content">
        <form action="{% url 'base:transfer' %}" method="POST" id="transferForm" >
           {% csrf_token %}
          <div class="modal-header">
             <h5 class="modal-title transferTitle" id="exampleModalCenterTitle">Transfer</h5>
             <button type="button" class="close" data-dismiss="modal" aria-label="Close">
             <span aria-hidden="true">&times;</span>
             </button>
          </div>
          <div class="modal-body">
                <div>
                    <label for="">Account Number</label>
                    <input type="text" name="accountNumber" id="transferAN" class="form-control" onkeyup="verifyAccount(this)">
                    <small class="font-weight-bolder anDetails" id=""></small>
                </div>
              
                  <div>
                    <label for="">Amount</label>
                    <input type="number" name="amount" id="transferAmount" class="form-control" min="0" max="{{user.account.balance}}">
                  </div>
          </div>
          <div class="modal-footer">
             <button type="submit" class="btn btn-primary actionTBtn" disabled>Transfer</button>
          </div>
        </form>
       </div>
    </div>
 </div>

transactions/templates/transactions.html
{% extends 'partials/_layout.html' %} 
{% load static humanize %}
{% block page_title %} Transactions {% endblock %}
{% block content %}

{% include 'partials/_sidebar.html' %}
{% include 'partials/_navbar.html' %}
<div class="content-page">
  <div class="messageAlert">
    {% for message in messages %}
    <div class="alert text-white bg-primary" role="alert">
      <div class="iq-alert-text">{{message}}</div>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <i class="ri-close-line"></i>
      </button>
    </div>
    {% endfor %}
  </div>

  <div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
           <div class="card">
              <div class="card-header d-flex justify-content-between">
                 <div class="header-title">
                    <h4 class="card-title">Transactions</h4>
                 </div>
              </div>
              <div class="card-body">
                 <div class="d-flex justify-content-between">
                  <p>Displays the list of transactions you've done from time to time.</p>
                  <div>
                     <a href="#" class="btn btn-danger" target="_blank">Download PDF</a>
                  </div>
                 </div>
                 <div class="table-responsive">
                    <table id="datatable" class="table data-tables table-striped">
                       <thead>
                          <tr class="ligth">
                             <th>S/N</th>
                             <th>Description</th>
                             <th>Type</th>
                             <th>Date</th>
                          </tr>
                       </thead>
                       <tbody>
                           {% for transaction in transactions %}
                          <tr>
                             <td>{{forloop.counter}}</td>
                             <td>{{transaction.desc}}</td>
                             <td>{{transaction.type}}</td>
                             <td>{{transaction.created_at}}</td>
                          </tr>
                          {% endfor %}
                       </tbody>
                       <tfoot>
                          <tr>
                            <th>S/N</th>
                            <th>Description</th>
                            <th>Type</th>
                            <th>Date</th>
                          </tr>
                       </tfoot>
                    </table>
                 </div>
              </div>
           </div>
        </div>
     </div>
    <!-- Page end  -->
  </div>
</div>

{% endblock %} {% block customscripts %}
<script>

</script>

{% endblock customscripts %}